### PR TITLE
Editorial changes

### PR DESCRIPTION
**Pull request by NellBrown**
Hi @sdwilkes - I've made all of Jess' changes to the six pages within the Discover Domesday section.

### CODE REVIEW

**Comment by sdwilkes** [comment]
@NellBrown All looks good, Nell. I won't merge it until you've finished the other changes (otherwise we'll have to create another branch). So once you've changed the next section let me know and I'll check those too.

**Comment by NellBrown** [comment]
@sdwilkes just done the World of Domesday section

**Comment by sdwilkes** [comment]
@NellBrown Hi Nell, these look good. If that's all the changes I'll ask Andy to pop them on TEST so we can double check them in the browser.

**Comment by NellBrown** [comment]
@sdwilkes I just realised I forgot to change the 'date modified' so don't ask him yet!

**Comment by NellBrown** [comment]
@sdwilkes Done!

**Pull request merged**
